name: 'Get & Cache Depedencies'
description: 'Get the depencies (via npm) and cache it'
inputs:
    caching:
        description: 'A parameter that will define whether to cache or not'
        required: false
        default: 'true'
outputs:
    used-cache:
        description: 'used cached'
        value: ${{ steps.install.outputs.cache }}
runs:
    using: 'composite'
    steps: 
        -   name: Cache dependencies
            if: inputs.caching == 'true'
            id: cache
            uses: actions/cache@v3
            with:
                path: node_modules
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
        -   name: Install dependencies
            id: install
            if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
            run: |
                npm ci
                echo "cache=${{ inputs.caching }}" >> $GITHUB_OUTPUT
            shell: bash